version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    depends_on:
      - db  
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: product
      DB_PASSWORD: product
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/log:/var/log
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"  # RabbitMQ management UI (Web UI)
      - "5672:5672"    # RabbitMQ default port for AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data for RabbitMQ

  product-management-service:
    build: ./backend/services/product-management
    container_name: product-management
    restart: always
    environment:
      DATABASE_URL: postgresql://product:product@pgbouncer:6432/product
      SECRET_KEY: kankan_secret_+123445
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - pgbouncer
    ports:
      - "8001:8001"

  uploader-service:
    build: ./backend/services/uploader
    container_name: uploader
    restart: always
    environment:
      PRODUCT_API_URL: http://product-management-service:8001
      UPLOAD_DIR: /app/s3  
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - product-management-service
    ports:
      - "8002:8002"
    volumes:
      - ./s3:/app/s3  

  workers:
    build: ./backend/services/worker
    container_name: workers
    ports:
      - "8006:8006"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DIR: /app/s3  
      DATABASE_URL: postgresql://product:product@pgbouncer:6432/product
      PRODUCT_API_URL: http://product-management-service:8001
    restart: always
    volumes:
      - ./s3:/app/s3  

  frontend:
    build: ./frontend  # Add frontend directory
    container_name: frontend
    restart: always
    depends_on:
      - product-management-service
    ports:
      - "5173:5173"  # Expose Vite default port
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid sharing node_modules between host and container

volumes:
  postgres_data:
  rabbitmq_data:
    driver: local
